#!/usr/bin/env python3

import boto3
import sys
attrbs = {
    'endpoint_url': 'http://localhost:8001'
}
if len(sys.argv) == 2:
    if "prod" in sys.argv[1]:
        attrs = {}
dynamodb = boto3.client('dynamodb',**attrbs)
table_name = 'ThinkspaceMessage'
response = dynamodb.create_table(
    TableName=table_name,
    AttributeDefinitions=[
        {
            'AttributeName': 'PartitionKey',
            'AttributeType': 'S'
        },
        {
            'AttributeName': 'SecondaryKey',
            'AttributeType': 'S'
        },
    ],

    KeySchema=[
        {
            'AttributeName': 'PartitionKey',
            'KeyType': 'HASH'
        },
        {
            'AttributeName': 'SecondaryKey',
            'KeyType': 'RANGE'
        },
    ],
    ##GlobalSecondaryIndexes=[
    ##],
    BillingMode='PROVISIONED',
    ProvisionedThroughput={
        'ReadCapacityUnits': 5,
        'WriteCapacityUnits': 5
    },
)